[project]
name = "planetoids"
version = "0.1.0"
description = "Guided project from boot.dev. Instructor: Sarah Schulte"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "pygame==2.6.1",
]
